import { useEffect, useRef, useState } from 'react'
import { FiArrowUpRight, FiBox, FiCheckCircle, FiCode, FiCpu, FiDatabase, FiGitBranch, FiLayers, FiLock, FiMail, FiPhone, FiSearch, FiServer, FiZap } from 'react-icons/fi'
import { FaJava, FaLinkedinIn } from 'react-icons/fa'

const services = [['User Service', 'Identity and customer profiles', <FiServer />], ['Product Service', 'Catalog and inventory ownership', <FiBox />], ['Order Service', 'Order orchestration with OpenFeign', <FiGitBranch />], ['Payment Service', 'Payment simulation and transaction flow', <FiZap />]]
const techRings = [['React', 'Vite', 'JavaScript', 'Framer Motion'], ['Java', 'Spring Boot', 'Eureka', 'OpenFeign'], ['JWT', 'Kafka', 'MySQL', 'SLF4j'], ['JUnit', 'Mockito', 'SonarCloud', 'React Router']]

export default function Dashboard() {
  const toolkitRef = useRef(null)
  const [toolkitInFocus, setToolkitInFocus] = useState(false)
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => setToolkitInFocus(entry.isIntersecting), { threshold: 0.55 })
    if (toolkitRef.current) observer.observe(toolkitRef.current)
    return () => observer.disconnect()
  }, [])
  return <main className="page showcase-page">
    <section className="contact-strip"><div><p className="eyebrow">Let’s build something useful</p><h2>Get in touch.</h2></div><div className="contact-links"><a href="mailto:prathamchandra2001@gmail.com"><FiMail /> prathamchandra2001@gmail.com</a><a href="tel:+919421809466"><FiPhone /> +91 9421809466</a><a href="http://www.linkedin.com/in/prathamesh-chandekar/" target="_blank" rel="noreferrer"><FaLinkedinIn /> LinkedIn <FiArrowUpRight /></a></div></section>
    <section className="console-hero"><FaJava className="java-backdrop" aria-hidden="true" /><div><p className="eyebrow">Engineering showcase</p><h1>From interface<br />to <em>event flow.</em></h1><p>This portfolio project pairs a deployment-ready React experience with a Spring Boot ecommerce system deliberately migrated from monolith to microservices.</p><a className="button primary" href="https://github.com/pratham1c1/Ecommerce_Microservices" target="_blank" rel="noreferrer">View backend on GitHub <FiArrowUpRight /></a></div><div className="skill-orbit"><FiCpu /><span>Full-stack architecture</span><i className="electron electron-one"><b /></i><i className="electron electron-two"><b /></i><i className="electron electron-three"><b /></i><i className="electron electron-four"><b /></i></div></section>
    <section className="showcase-section"><p className="eyebrow">System architecture</p><h2>Services that own their work.</h2><p className="intro">The backend was migrated from a monolith into independently deployable services. Eureka provides discovery, OpenFeign supports service-to-service communication, Kafka handles events, and an API Gateway applies JWT authentication at the edge.</p><div className="backend-flow"><div className="client-node"><FiCode /><b>React frontend</b><span>GitHub Pages-ready</span></div><div className="connector request-connector"><i /></div><div className="gateway-node"><FiLock /><b>API Gateway</b><span>JWT authentication</span></div><div className="fan-flow">{services.map(([name]) => <i key={name} />)}</div><div className="service-row">{services.map(([name, detail, icon]) => <article key={name}><span>{icon}</span><b>{name}</b><small>{detail}</small></article>)}</div><div className="data-row"><div><FiDatabase /> MySQL · database per service</div><div><FiZap /> Apache Kafka · event-driven messaging</div><div><FiServer /> Eureka · service discovery</div></div></div></section>
    <section className="showcase-section journey"><p className="eyebrow">User journey</p><h2>One intent, a considered flow.</h2><div className="journey-flow"><article><span>01</span><FiSearch /><h3>Discover</h3><p>Visitors browse responsive product data from a mock-first React storefront.</p></article><article><span>02</span><FiLayers /><h3>Request</h3><p>In live mode, the frontend sends a request through the authenticated gateway.</p></article><article><span>03</span><FiGitBranch /><h3>Orchestrate</h3><p>Order workflows coordinate user, product, payment, and inventory services.</p></article><article><span>04</span><FiCheckCircle /><h3>Confirm</h3><p>Kafka-powered events and focused data stores complete the commerce lifecycle.</p></article></div></section>
    <section className="showcase-section" ref={toolkitRef}><p className="eyebrow">Technology toolkit</p><h2>Practical engineering, end to end.</h2><p className="toolkit-hint">Scroll into view to assemble the technology constellation.</p><div className={`tech-system constellation ${toolkitInFocus ? 'expanded' : ''}`}>{techRings.map((ring, index) => <div className={`tech-ring tech-ring-${index + 1}`} key={ring[0]}>{ring.map((technology, itemIndex) => <b className={`tech-item item-${itemIndex + 1}`} key={technology}>{technology}</b>)}</div>)}</div><div className="quality-grid"><article><FiGitBranch /><h3>Monolith → microservices</h3><p>Clear domain boundaries enable independently scalable deployments.</p></article><article><FiCheckCircle /><h3>Quality-led delivery</h3><p>JUnit and Mockito test suites target 90%+ coverage with SonarCloud quality gates.</p></article><article><FiCode /><h3>Frontend craft</h3><p>Responsive React UI, reusable components, accessible interactions, and GitHub Pages support.</p></article></div></section>
    <section className="coming-soon"><i className="ai-spark spark-one" /><i className="ai-spark spark-two" /><div><p className="eyebrow">AI touch, coming soon</p><h2>Search that understands intent.</h2><p>The next iteration will combine LLM APIs and retrieval-augmented generation (RAG), letting people find products using natural, human language instead of only keywords.</p></div><div className="rag-flow"><span>“I need a quiet setup for remote work.”</span><i>→</i><b>LLM + RAG search</b><i>→</i><span>Relevant products, explained</span></div></section>
  </main>
}
