import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { FiSearch, FiSliders } from 'react-icons/fi'
import SectionTitle from '../components/SectionTitle'
import ProductCard from '../components/ProductCard'
import { categories } from '../mock/data'
import { getProducts } from '../services/api'

export default function Store() { const [searchParams, setSearchParams] = useSearchParams(); const [items, setItems] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const category = searchParams.get('category') || 'All'; useEffect(() => { getProducts().then(setItems).catch(() => setItems([])).finally(() => setLoading(false)) }, []); const visible = useMemo(() => items.filter(p => (category === 'All' || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase())), [items, category, query]); return <main className="page"><SectionTitle eyebrow="The storefront" title="Curated for momentum." text="Mock mode for Demo products" /><div className="store-toolbar"><div className="search"><FiSearch /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search the collection" aria-label="Search products" /></div><span><FiSliders /> {visible.length} products</span></div><div className="filters"><button className={category === 'All' ? 'active' : ''} onClick={() => setSearchParams({})}>All</button>{categories.map(c => <button key={c.name} className={category === c.name ? 'active' : ''} onClick={() => setSearchParams({ category: c.name })}>{c.name}</button>)}</div>{loading ? <p className="empty">Loading the collection…</p> : <div className="product-grid store-grid">{visible.map(product => <ProductCard key={product.id} product={product} />)}</div>}{!loading && !visible.length && <p className="empty">No products match that search.</p>}</main> }
